-- DROP DATABASE IF EXISTS UHRWERK_METASTORE;
CREATE DATABASE IF NOT EXISTS UHRWERK_METASTORE_TEST2;
GRANT SELECT, INSERT, UPDATE, DELETE ON UHRWERK_METASTORE_TEST2.* TO 'UHRWERK_USER'@'%';
FLUSH PRIVILEGES;