DROP TABLE IF EXISTS UHRWERK_METASTORE.PARTITION_LOG;
DROP TABLE IF EXISTS UHRWERK_METASTORE.TARGET_CONFIG;
DROP TABLE IF EXISTS UHRWERK_METASTORE.DEPENDENCY_CONFIG;
DROP TABLE IF EXISTS UHRWERK_METASTORE.TABLE_PARTITION_INFO;
DROP TABLE IF EXISTS UHRWERK_METASTORE.STEP_CONFIG;
DROP TABLE IF EXISTS UHRWERK_METASTORE.TABLE_INFO;
DROP TABLE IF EXISTS UHRWERK_METASTORE.CONNECTION_CONFIG;
