# For testing only a yelp source from db and a datalake

- name: "tpcdi_mysql"
  jdbc:
    jdbc_url: 'jdbc:mysql://my-mysql:3306/db_uhrwerk_generator'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: password2

- name: "local_fs_lake"
  file:
    path: './example_datalake'