area: "staging"
vertical: "retail"
table: "productDim"
version: "1.0"
class_name: "io.qimia.uhrwerk.example.retail_examples.HashLoad"
parallelism: 1
max_bulk_size: 1

sources:
  - connection_name: "retail_mysql"
    path: "qimia_oltp.products"
    format: "jdbc"
    version: "1.0"

targets:
  - connection_name: "retail_mysql"
    format: "jdbc"