# For testing only a yelp source from db and a datalake

- name: "yelp_mysql"
  jdbc:
    jdbc_url: 'jdbc:mysql://localhost:53306/yelp_db'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: 61ePGqq20u9TZjbNhf0

- name: "local_fs_lake"
  file:
    path: '/spark_datadir/example_datalake'

- name: "local_fs_source"
  file:
    path: '/spark_datadir/example_dataset'

- name: "yelp_dwh"
  jdbc:
    jdbc_url: 'jdbc:mysql://localhost:53306'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: 61ePGqq20u9TZjbNhf0

- name: "retail_mysql"
  jdbc:
    jdbc_url: 'jdbc:mysql://localhost:43306/'
    jdbc_driver: 'com.myqsl.cj.jdbc.Driver'
    user: root
    pass: mysql