# For testing only a yelp source from db and a datalake

- name: "yelp_mysql"
  jdbc:
    jdbc_url: 'jdbc:mysql://localhost:53306/yelp_db'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: mysql

- name: "local_fs_lake"
  file:
    path: './example_datalake'

- name: "local_fs_source"
  file:
    path: './example_dataset'

- name: "yelp_dwh"
  jdbc:
    jdbc_url: 'jdbc:mysql://localhost:53306/yelp_dwh'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: mysql