USE UHRWERK_METASTORE_TEST2;
--  SOURCE --
ALTER TABLE SOURCE
    ADD COLUMN view_name VARCHAR(128) NULL AFTER auto_load;

-- DEPENDENCY --
ALTER TABLE DEPENDENCY
    ADD COLUMN auto_load BOOLEAN NOT NULL DEFAULT TRUE AFTER dependency_variables;
