version: "3.2"

services:
  adminer-uhrwerk-metastore:
    image: adminer
    restart: always
    container_name: adminer-uhrwerk-metastore
    depends_on:
      - mysql-uhrwerk-metastore
    ports:
      - 9080:8080

  mysql-uhrwerk-metastore:
    image: mysql:8.0.29
    restart: always
    container_name: mysql-uhrwerk-metastore
    ports:
      - 53306:3306
    volumes:
      - ./mysql_datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "61ePGqq20u9TZjbNhf0"
      MYSQL_DATABASE: "UHRWERK_METASTORE"
      MYSQL_USER: "UHRWERK_USER"
      MYSQL_PASSWORD: "Xq92vFqEKF7TB8H9"
    command: "--default-authentication-plugin=mysql_native_password --innodb_buffer_pool_size=1G --innodb_log_file_size=256M --innodb_flush_log_at_trx_commit=1 --innodb_flush_method=O_DIRECT --explicit_defaults_for_timestamp=1"

  spark-master:
    image: uhrwerk/spark-master:3.2.1-hadoop2.7
    restart: always
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./spark_datadir:/spark_datadir
      - ./spark_logs:/spark_logs
      - ./spark_jars:/spark_jars
      - ./spark_configs:/spark_configs

  spark-worker-1:
    image: uhrwerk/spark-worker:3.2.1-hadoop2.7
    restart: always
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    volumes:
      - ./spark_datadir:/spark_datadir
      - ./spark_logs:/spark_logs
      - ./spark_jars:/spark_jars
      - ./spark_configs:/spark_configs
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-history-server:
    image: uhrwerk/spark-history-server:3.2.1-hadoop2.7
    restart: always
    container_name: spark-history-server
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - 18080:18080
    volumes:
      - ./spark_logs:/spark_logs