version: "3.2"
services:
  spark-master:
    image: uhrwerk/spark-master:3.0.1-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./spark_datadir:/spark_datadir
      - ./spark_logs:/spark_logs
      - ./spark_jars:/spark_jars

  spark-worker-1:
    image: uhrwerk/spark-worker:3.0.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    volumes:
      - ./spark_datadir:/spark_datadir
      - ./spark_logs:/spark_logs
      - ./spark_jars:/spark_jars
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-history-server:
    image: uhrwerk/spark-history-server:3.0.1-hadoop2.7
    container_name: spark-history-server
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - 18080:18080
    volumes:
      - ./spark_logs:/spark_logs
