area: "staging"
vertical: "retail"
table: "productDim"
version: "1.0"
parallelism: 1
max_bulk_size: 1

sources:
  - connection_name: "retail_mysql"
    path: "qimia_oltp.products"
    format: "jdbc"
    version: "1.0"
    select:
      query: "retail_examples/productDim-loader.sql"

targets:
  - connection_name: "retail_mysql"
    format: "jdbc"