-- DROP DATABASE IF EXISTS UHRWERK_METASTORE;
CREATE DATABASE IF NOT EXISTS UHRWERK_METASTORE;
CREATE USER IF NOT EXISTS 'UHRWERK_USER'@'%' IDENTIFIED BY 'Xq92vFqEKF7TB8H9';
GRANT SELECT, INSERT, UPDATE, DELETE ON UHRWERK_METASTORE.* TO 'UHRWERK_USER'@'%';
FLUSH PRIVILEGES;