secrets:
  - type: aws
    name: yelp_db_passwd
    aws_secret_name: uhrwerk/yelp_test/yelp_db_passwd
    aws_region: eu-west-1

connections:
  - name: "yelp_mysql"
    type: jdbc
    jdbc_url: 'jdbc:mysql://127.0.0.1:53306/yelp_db'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    password: '!secret:yelp_db_passwd'

  - name: "uhrwerk_test_s3"
    type: s3
    path: 's3a://qimiaio-uhrwerk-dev-test01/uhrwerk-example/example_datalake'