# For testing only a yelp source from db and a datalake

- name: "yelp_mysql"
  jdbc:
    jdbc_url: 'jdbc:mysql://127.0.0.1:53306/yelp_db'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: 61ePGqq20u9TZjbNhf0

- name: "local_fs_lake"
  file:
    path: 'uhrwerk-example/example_datalake'

- name: "local_fs_source"
  file:
    path: 'uhrwerk-example/example_dataset'

- name: "yelp_dwh"
  jdbc:
    jdbc_url: 'jdbc:mysql://127.0.0.1:53306'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: 61ePGqq20u9TZjbNhf0

- name: "retail_mysql"
  jdbc:
    jdbc_url: 'jdbc:mysql://localhost:43306/'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: mysql

- name: "qimia_oltp"
  jdbc:
    jdbc_url: 'jdbc:mysql://127.0.0.1:43306/qimia_oltp'
    jdbc_driver: 'com.mysql.cj.jdbc.Driver'
    user: root
    pass: mysql
