area: "dwh"
vertical: "sales"
table: "productDim"
version: "1.0"

dependencies:
  - area: "staging"
    vertical: "retail"
    table: "productDim"
    format: "jdbc"
    version: "1.0"

targets:
  - connection_name: "retail_examples"
    format: "jdbc"