INSERT INTO PARTITION_DEPENDENCY (id, partition_id, dependency_partition_id)
VALUES (123, 234, 345);

DELETE FROM PARTITION_DEPENDENCY;
DELETE FROM PARTITION_;

DELETE FROM DEPENDENCY;
DELETE FROM SOURCE ;
DELETE FROM TARGET;
DELETE FROM TABLE_;
DELETE FROM `CONNECTION`;