package io.qimia.uhrwerk.config;

import io.qimia.uhrwerk.common.model.Connection;
import io.qimia.uhrwerk.common.model.Dag;
import io.qimia.uhrwerk.common.model.Metastore;
import io.qimia.uhrwerk.common.model.Table;
import org.junit.jupiter.api.Test;

class OldConfigBuilderTest {
  @Test
  public void connectionBuilderTest() {

    Connection[] connection = (new OldConnectionBuilder())
            .name("S3")
              .s3()
                .path("S3Path")
                .secretId("ID")
                .secretKey("key")
            .name("JDBC")
              .jdbc()
                .jdbcUrl("url")
                .jdbcDriver("driver")
                .user("user")
                .pass("pass")
            .name("file")
              .file()
                .path("filePath")
            .build();
    for (Connection c : connection)
          {
            System.out.println(c);
    }

  }


  @Test
  public void tableBuilderTest() {

    Table table = (new OldTableBuilder())
            .area("TableArea")
            .vertical("TableVertical")
            .table("TableTable")
            .version("TableVersion")
            //.parallelism(2)
            //.maxBulkSize(2)
            .partition()
            .unit("hours")
            .size(4)
            .source()
            .connectionName("SourceConnection1")
            .path("SourcePath1")
            .format("parquet")
              .version("1.0")
              .partition()
                .unit("days")
                .size(10)
            .parallelLoad()
            .query("SELECT * FROM BLA1")
            .column("Column1")
            .num(10)
            .select()
            .query("config/table_test_2_select_query.sql")
            .column("created_at")
            .source()
            .connectionName("SourceConnection2")
            .path("SourcePath2")
            .format("parquet")
              .version("1.0")
              .partition()
                .unit("hours")
            .size(24)
            //.parallel_load()
            //  .query("SELECT * FROM BLA2")
            //  .column("Column2")
            //  .num(5)
            .select()
            .query("SELECT * FROM BLA3")
            .column("Column3")
            .target()
            .connectionName("TargetConnection1")
            .format("csv")
            .target()
            .connectionName("TargetConnection2")
            .format("parquet")
            .dependency()
            .area("DepArea1")
            .version("1.1")
            .vertical("DepVertical1")
            .table("DepTableTable1")
            .format("csv")
            .transform()
            .type("identity")
            .dependency()
            .area("DepArea2")
            .version("1.2")
            .vertical("DepVertical2")
            .table("DepTableTable2")
            .format("csv")
            .transform()
            .type("window")
            .partition()
            .size(5)
            .dependency()
            .area("DepArea3")
            .version("1.3")
            .vertical("DepVertical3")
            .table("DepTableTable3")
            .format("csv")
            .transform()
            .type("aggregate")
            .partition()
            .size(2)
            .dependency()
            .area("DepArea4")
            .version("1.4")
            .vertical("DepVertical4")
            .table("DepTableTable4")
            .format("json")
              .transform()
                .type("temporal_aggregate")
                .partition()
                  .size(4)
                  .unit("hours")
            .build();
      System.out.println(table);

  }

  @Test
  public void metastoreBuilderTest() {

    Metastore metastore = (new OldMetastoreBuilder())
            .jdbcUrl("url")
            .jdbcDriver("driver")
            .user("user")
            .pass("pass")
            .build();

    System.out.println(metastore);

  }

  @Test
  public void dagBuilderTest() {

    Dag dag = (new OldDagBuilder())
            .connection()
              .name("S3")
              .s3()
                .path("S3Path")
                .secretId("ID")
                .secretKey("key")
            .connection()
              .name("JDBC")
              .jdbc()
                .jdbcUrl("url")
                .jdbcDriver("driver")
                .user("user")
                .pass("pass")
            .connection()
              .name("file")
              .file()
                .path("filePath")
            .table()
              .area("TableArea")
              .vertical("TableVertical")
            .table("TableTable")
            .version("TableVersion")
            .parallelism(2)
            .maxBulkSize(2)
            .partition()
            .unit("days")
            .size(4)
            .source()
            .connectionName("SourceConnection1")
            .path("SourcePath1")
            .format("parquet")
              .version("1.0")
              .partition()
                .unit("days")
                .size(10)
            .parallelLoad()
            .query("SELECT * FROM BLA1")
            .column("Column1")
            .num(10)
            .select()
            .query("config/table_test_2_select_query.sql")
            .column("created_at")
            .source()
            .connectionName("SourceConnection2")
            .path("SourcePath2")
            .format("csv")
              .version("1.0")
              .partition()
                .unit("hours")
            .size(24)
            //.parallel_load()
            //  .query("SELECT * FROM BLA2")
            //  .column("Column2")
            //  .num(5)
            .select()
            .query("SELECT * FROM BLA3")
            .column("Column3")
            .target()
            .connectionName("TargetConnection1")
            .format("json")
            .target()
            .connectionName("TargetConnection2")
            .format("csv")
            .dependency()
            .area("DepArea1")
            .version("1.1")
            .vertical("DepVertical1")
            .table("DepTableTable1")
            .format("parquet")
            .transform()
            .type("identity")
            .dependency()
            .area("DepArea2")
            .version("1.2")
            .vertical("DepVertical2")
            .table("DepTableTable2")
            .format("csv")
            .transform()
            .type("window")
            .partition()
            .size(5)
            .dependency()
            .area("DepArea3")
            .version("1.3")
            .vertical("DepVertical3")
            .table("DepTableTable3")
            .format("json")
            .transform()
            .type("aggregate")
            .partition()
            .size(2)
            .dependency()
            .area("DepArea4")
            .version("1.4")
            .vertical("DepVertical4")
            .table("DepTableTable4")
            .format("jdbc")
              .transform()
                .type("temporal_aggregate")
                .partition()
                  .size(4)
                  .unit("hours")
            .build();

    System.out.println(dag);

  }

}