DELETE FROM UHRWERK_METASTORE.PARTITION_DEPENDENCY;
DELETE FROM UHRWERK_METASTORE.PARTITION_;
DELETE FROM UHRWERK_METASTORE.DEPENDENCY;
DELETE FROM UHRWERK_METASTORE.TARGET;
DELETE FROM UHRWERK_METASTORE.SOURCE;
DELETE FROM UHRWERK_METASTORE.TABLE_;
DELETE FROM UHRWERK_METASTORE.CONNECTION;