USE UHRWERK_METASTORE;
DROP TABLE IF EXISTS PARTITION_DEPENDENCY;
DROP TABLE IF EXISTS PARTITION_;
DROP TABLE IF EXISTS DEPENDENCY;
DROP TABLE IF EXISTS TARGET;
DROP TABLE IF EXISTS SOURCE;
DROP TABLE IF EXISTS TABLE_;
DROP TABLE IF EXISTS CONNECTION;
DROP TABLE IF EXISTS SECRET_;